dataset_conf:
    filter_conf:
        max_length: 2048
        min_length: 0
        token_max_length: 200
        token_min_length: 1
        max_output_input_ratio: 1
        min_output_input_ratio: 0.0005
    resample_conf:
        resample_rate: 16000
    speed_perturb: false
    reverb_prob: 0.2
    noise_prob: 0.3
    feats_type: 'fbank'
    fbank_conf:
        num_mel_bins: 40
        frame_shift: 10
        frame_length: 25
        dither: 1.0
    spec_aug: false
    spec_aug_conf:
        num_t_mask: 1
        num_f_mask: 1
        max_t: 20
        max_f: 10
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    sort: false
    batch_conf:
        batch_size: 256

model:
    hidden_dim: 64
    preprocessing:
        type: linear
    backbone:
        type: tcn
        ds: true
        num_layers: 4
        kernel_size: 8
        dropout: 0.1

optim: adam
optim_conf:
    lr: 0.001
    weight_decay: 0.0001

training_config:
    grad_clip: 5
    max_epoch: 80
    log_interval: 10

