dataset_conf:
    filter_conf:
        max_length: 2048
        min_length: 0
    resample_conf:
        resample_rate: 16000
    speed_perturb: false
    feature_extraction_conf:
        feature_type: 'fbank'
        num_mel_bins: 40
        frame_shift: 10
        frame_length: 25
        dither: 1.0
    spec_aug: false
    spec_aug_conf:
        num_t_mask: 2
        num_f_mask: 2
        max_t: 50
        max_f: 30
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    batch_conf:
        batch_size: 256

model:
    hidden_dim: 64
    preprocessing:
        type: linear
    backbone:
        type: tcn
        ds: false
        num_layers: 4
        kernel_size: 8
        dropout: 0.1

optim: adam
optim_conf:
    lr: 0.001
    weight_decay: 0.0001

training_config:
    grad_clip: 5
    max_epoch: 80
    log_interval: 10

