name: "Check and Publish Docs"
on:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # add .nojekyll to notice Pages use the _* dirs
    - name: copy the generated site
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        mkdir public
        touch public/.nojekyll
        cp -r docs/_build/html/* public/

    # push to gh-pages branch
    - name: github pages deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: public
